### ISSUE TITLE
Komodo 9 support

### ISSUE THREAD

**Issue by randomsock** [rkgarcia/JadeLang4Komodo#2]
I do a lot of Jade in Komodo Edit so always loved your highlighter, but Komodo 9 says it's not compatible - any chance you could update?

**Comment by rkgarcia** [comment]
Of course, i'm writing the new plugin =)

**Comment by randomsock** [comment]
Hey, thanks for that :smile:   Unfortunately though, I think Komodo is moving faster than we are - I just tried your 0.2 xpi with the current Komodo Edit 9.2 and it won't install:

![capture](https://cloud.githubusercontent.com/assets/8095654/8997611/4590ec22-371b-11e5-90e3-25ce19462bce.PNG)

Any ideas?

**Comment by rkgarcia** [comment]
I will work in the new versión... follow this issue :)

**Comment by randomsock** [comment]
Should have closed this again a while ago - works on 9.3 :)
